[package]
name = "lil-wrapper-zed"
description = "Zed extension for the native Lil Wrapper language server"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
zed_extension_api = "=0.7.0"
