id = "lil-wrapper"
name = "Lil Wrapper"
version = "0.1.1"
schema_version = 1
authors = ["Matt Luedke <mluedke.ds@gmail.com>"]
description = "Wrap comments and text to a configurable column."
repository = "https://github.com/hypothesi/lil-wrapper"
license = "MIT"

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["hypothesi", "lil-wrapper", "releases", "download", "**"]

[language_servers.lil-wrapper]
name = "Lil Wrapper Language Server"
code_action_kinds = ["refactor.rewrite"]
languages = [
  "AsciiDoc",
  "AutoHotkey",
  "C",
  "C++",
  "CMake",
  "CSharp",
  "Clojure",
  "CoffeeScript",
  "Crystal",
  "CSS",
  "D",
  "Dart",
  "Dockerfile",
  "Elisp",
  "Elixir",
  "Elm",
  "ERB",
  "FSharp",
  "Git Commit",
  "Go",
  "GraphQL",
  "Groovy",
  "Haskell",
  "HCL",
  "HTML",
  "HTML+ERB",
  "ini",
  "Java",
  "JavaScript",
  "JS+ERB",
  "JSON",
  "JSON5",
  "JSONC",
  "Julia",
  "LaTeX",
  "Lean 4",
  "LESS",
  "Lua",
  "Make",
  "Markdown",
  "MATLAB",
  "MDX",
  "Objective-C",
  "Pascal",
  "Perl",
  "PHP",
  "Plain Text",
  "PowerShell",
  "Prisma",
  "Prolog",
  "Properties",
  "Proto",
  "Pug",
  "PureScript",
  "Python",
  "R",
  "Racket",
  "reST",
  "Ruby",
  "Rust",
  "Scala",
  "Scheme",
  "SCSS",
  "Shell Script",
  "SQL",
  "Svelte",
  "Swift",
  "SystemVerilog",
  "TCL",
  "Terraform",
  "TOML",
  "TSX",
  "TypeScript",
  "Vue.js",
  "XML",
  "YAML",
  "YAML+ERB",
]

[language_servers.lil-wrapper.language_ids]
"AsciiDoc" = "asciidoc"
"AutoHotkey" = "autohotkey"
"C" = "c"
"C++" = "cpp"
"CMake" = "cmake"
"CSharp" = "csharp"
"Clojure" = "clojure"
"CoffeeScript" = "coffeescript"
"Crystal" = "crystal"
"CSS" = "css"
"D" = "d"
"Dart" = "dart"
"Dockerfile" = "dockerfile"
"Elisp" = "elisp"
"Elixir" = "elixir"
"Elm" = "elm"
"ERB" = "erb"
"FSharp" = "fsharp"
"Git Commit" = "git-commit"
"Go" = "go"
"GraphQL" = "graphql"
"Groovy" = "groovy"
"Haskell" = "haskell"
"HCL" = "hcl"
"HTML" = "html"
"HTML+ERB" = "erb"
"ini" = "ini"
"Java" = "java"
"JavaScript" = "javascript"
"JS+ERB" = "javascript"
"JSON" = "json"
"JSON5" = "json5"
"JSONC" = "jsonc"
"Julia" = "julia"
"LaTeX" = "latex"
"Lean 4" = "lean"
"LESS" = "less"
"Lua" = "lua"
"Make" = "make"
"Markdown" = "markdown"
"MATLAB" = "matlab"
"MDX" = "mdx"
"Objective-C" = "objective-c"
"Pascal" = "pascal"
"Perl" = "perl"
"PHP" = "php"
"Plain Text" = "plaintext"
"PowerShell" = "powershell"
"Prisma" = "prisma"
"Prolog" = "prolog"
"Properties" = "properties"
"Proto" = "proto"
"Pug" = "pug"
"PureScript" = "purescript"
"Python" = "python"
"R" = "r"
"Racket" = "scheme"
"reST" = "rst"
"Ruby" = "ruby"
"Rust" = "rust"
"Scala" = "scala"
"Scheme" = "scheme"
"SCSS" = "scss"
"Shell Script" = "shellscript"
"SQL" = "sql"
"Svelte" = "svelte"
"Swift" = "swift"
"SystemVerilog" = "systemverilog"
"TCL" = "tcl"
"Terraform" = "terraform"
"TOML" = "toml"
"TSX" = "typescriptreact"
"TypeScript" = "typescript"
"Vue.js" = "vue"
"XML" = "xml"
"YAML" = "yaml"
"YAML+ERB" = "yaml"
