[package]
name = "lil-wrapper-lsp"
description = "Native Rust language server for Lil Wrapper"
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
diff_match_patch = "=0.3.0"
lil-wrapper-core = { path = "../lil-wrapper-core" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
